-- To Create the Database Home Furniture Pvt Ltd.
CREATE DATABASE Homefurniturepvtltd;

-- To use the Database
use Homefurniturepvtltd;

-- To view the Structure of the Kaggle Dataset
desc dataset;

-- To view the Dataset
select * from Dataset;

-- To add primary key in dataset
ALTER TABLE Dataset
add primary key (SNo);

-- How many total rows are there 
select count(*) from Dataset;

-- Q.1 What is the Total Cost in each Category?
SELECT Category, SUM(Cost) AS Total_Cost
FROM dataset
GROUP BY Category;

-- Q.2 What is the Total Sales and Revenue in each Category?
SELECT Category, SUM(Sales) AS Total_Sales, SUM(Revenue) AS Total_Revenue
FROM dataset
GROUP BY Category;

-- Q.3 What is the Total Profit in each Category?
SELECT Category, SUM(Profit_Margin) AS Total_Profit
FROM dataset
GROUP BY Category;

-- Q.4 What is the Total Sales, Revenue and Profit in different store types?
SELECT Store_Type, SUM(Sales) AS Total_Sales, SUM(Revenue) AS Total_Revenue, SUM(Profit_Margin) AS Total_Profit
FROM dataset
GROUP BY Store_Type;

-- Q.5 What is the Total Sales, Revenue and Profit in different Locations?
SELECT location, SUM(Sales) AS Total_Sales, SUM(Revenue) AS Total_Revenue, SUM(Profit_Margin) AS Total_Profit
FROM dataset
GROUP BY location;

-- Q.6 What is Total delivery days in each Category?
SELECT Category, SUM(Delivery_Days) AS Total_Delivery_Days
FROM dataset
GROUP BY Category;

-- Q.7 What is Total Left out Stock in each Category?
SELECT Category, SUM(Inventory - Sales) AS Left_Out_Stock
FROM Dataset
GROUP BY Category;

-- Q.8) What is the average profit margin in each Category?
 SELECT Category, (AVG(Profit_Margin)) AS Profit_Margin
 FROM Dataset
 Group BY Category;
 
 -- Q.9) What is the average profit margin in each Brand?
 SELECT Brand, (AVG(Profit_Margin)) AS Profit_Margin
 FROM Dataset
 Group BY Brand;
 
 -- Q.10) What is the maximum profit among the given Brands?
 SELECT Brand, MAX(Profit_Margin) AS Max_Margin
 FROM Dataset
 Group BY Brand;
 
 -- Q.11) What is the minimum profit among the given Brands?
 SELECT Brand, ROUND(MIN(Profit_Margin)) AS Min_Profit
 FROM Dataset
 Group BY Brand;
 
-- Q.12) Which products are sold with the highest discount percentages?
SELECT Brand, Category,
MAX(Discount_Percentage) AS Max_Discount
FROM Dataset
GROUP BY Brand, Category
ORDER BY Max_Discount DESC;

-- Q.13) What is the average inventory level in different locations?
SELECT location,
AVG(Inventory) AS
Avg_Inventory
FROM Dataset
GROUP BY Location;

-- Q.14) Which Season yields the highest profit margins?
SELECT Season,
AVG(Profit_Margin) AS
Avg_Profit_Margin
FROM Dataset
GROUP BY Season
ORDER By Avg_Profit_Margin
DESC;

-- Q.15) How much revenue is generated by each payment method?
SELECT Transactions,
SUM(Revenue) AS Total_Revenue
FROM Dataset
GROUP BY Transactions
ORDER BY Total_Revenue DESC;

-- Q.16) Which Product have high inventory but low sales?
SELECT Brand, Category, Sales, Inventory
FROM Dataset
WHERE Sales <20 AND Inventory >100
ORDER BY Inventory DESC;

-- Q.17) Do products with fewer delivery days tend to have higher sales? 
SELECT Delivery_Days,
AVG(Sales) AS Avg_Sales
FROM Dataset
GROUP BY Delivery_Days
ORDER BY Delivery_Days;
